CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1)
OUTPUT_DIR: 'checkpoints/camvid'
LOG_DIR: 'logs'
WORKERS: 3
PRINT_FREQ: 10

DATASET:
  DATASET: camvid
  ROOT: data/
  TEST_SET: 'list/camvid/test.lst'
  TRAIN_SET: 'list/camvid/train.lst'
  NUM_CLASSES: 11
MODEL:
  NAME: p2at_m
  NUM_OUTPUTS: 2
  PRETRAINED: "checkpoints/cityscapes/P2AT_Medium_Cityscapes_train.pth"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  AUX_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 960
  - 720
  BASE_SIZE: 960
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 140
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.004
  WD: 0.0005
  EPS: 1e-08
  BETAS: (0.9, 0.999)
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 960
  - 720
  BASE_SIZE: 960
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
